language: cpp

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt562 -y
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
    
install: 
  - sudo apt-get -qq install g++-4.8 libc6-i386 qt56tools qt56svg qt56webkit qt56script
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"x
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd src/
  - echo "#define BUILD ""$TRAVIS_BUILD_NUMBER" > build_number.h
  - echo "#define RELEASE \"Travis CI\"" > release.h
  - qmake QOwnNotes.pro CONFIG+=$CONFIG PREFIX=/usr
  - make -j4
  - sudo make INSTALL_ROOT=appdir install ; sudo chown -R $USER appdir ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Q*.AppImage https://transfer.sh/QOwnNotes-git.$(git rev-parse --short HEAD)-x86_64.AppImage
